import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#000000",
  },
  addButton: {
    backgroundColor: "#F7AB42",
    minWidth: 160,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1A1A1A",
  },
  divider: {
    width: "100%",
    height: 3,
    backgroundColor: "#F1B156",
  },
  listWrapper: {
    flex: 1,
  },
  listContent: {
    paddingTop: 30,
    paddingHorizontal: 28,
    paddingBottom: 30,
  },
  friendRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 28,
  },
  friendLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 16,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    marginRight: 16,
  },
  friendInfo: {
    flex: 1,
  },
  friendName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 2,
  },
  friendBalance: {
    fontSize: 16,
    fontWeight: "600",
  },
  negativeText: {
    color: "#D84444",
  },
  positiveText: {
    color: "#2F9446",
  },
  neutralText: {
    color: "#111111",
  },
  selectButton: {
    backgroundColor: "#F7AB42",
    minWidth: 150,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  selectButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1A1A1A",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.08)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  modalCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#F8F0E5",
    borderRadius: 24,
    paddingTop: 24,
    paddingHorizontal: 18,
    paddingBottom: 22,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111111",
    textAlign: "center",
    marginBottom: 26,
  },
  modalRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  modalLabel: {
    width: 96,
    fontSize: 18,
    color: "#222222",
  },
  modalInput: {
    flex: 1,
    height: 42,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D7D7D7",
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 16,
    color: "#111111",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingHorizontal: 18,
  },
  modalButton: {
    backgroundColor: "#F7AB42",
    minWidth: 110,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1A1A1A",
  },
  splitModalCard: {
    width: "100%",
    maxWidth: 390,
    backgroundColor: "#F8F0E5",
    borderRadius: 24,
    paddingTop: 22,
    paddingHorizontal: 18,
    paddingBottom: 22,
  },
  splitModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111111",
    textAlign: "center",
    marginBottom: 28,
  },
  splitRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  splitLabel: {
    width: 165,
    fontSize: 18,
    color: "#222222",
  },
  splitInput: {
    flex: 1,
    height: 42,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D7D7D7",
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 16,
    color: "#111111",
  },
  payerTitle: {
    textAlign: "center",
    fontSize: 18,
    color: "#111111",
    marginTop: 8,
    marginBottom: 20,
  },
  payerOptions: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
  },
  payerOption: {
    flexDirection: "row",
    alignItems: "center",
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#5FA15A",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#2F9446",
  },
  payerText: {
    fontSize: 18,
    color: "#222222",
  },
  splitDivider: {
    height: 3,
    backgroundColor: "#F1B156",
    marginHorizontal: -18,
    marginBottom: 18,
  },
});

export default styles;